FROM python:3.11.3-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

ENV DOCKER_ENV=true
ENV DATABASE_CONFIG_FILE=configs/databases/mongodb.yaml

EXPOSE 8000

COPY . .

CMD ["python", "-m", "src.server"]
